# De60 BLE Configuration

# Enable Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# Battery
CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER=y

# Deep Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# USB
CONFIG_ZMK_USB_LOGGING=n
